Feature/new lock
Wavemind/liwi-backend pull request #57
Opened 2021-09-14 12:21 UTC by ManuBarchich

2021-09-15 13:38 UTC, quentingirard requested changes

2021-09-15 13:38 UTC, quentingirard commented on app/javascript/apps/diagram/components/Diagram/index.js
> +    // if (readOnly) {
💩

2021-09-15 13:38 UTC, quentingirard commented on app/javascript/apps/form/QuestionForm/questionForm.js
> +                      disabled={deployedMode}
Voulu que certains champs soient bloqués et d'autres pas ?

2021-09-15 13:38 UTC, quentingirard commented on app/javascript/apps/form/QuestionsSequenceForm/index.js
> +                      // disabled={deployedMode}
Rajoute des TODO pour ne pas oublier de les supprimer plus tard

2021-09-15 13:38 UTC, quentingirard commented on app/models/node.rb
> +    # false
Pourquoi t'as commenté ?

2021-09-15 13:38 UTC, quentingirard commented on app/views/versions/_form.html.erb
> +    <%= f.input :in_prod, as: :boolean, label: t('activerecord.attributes.version.in_prod') %>
obligé de mettre le label ?. Normalement simple_form le fait automatiquement

2021-09-16 11:43 UTC, ManuBarchich commented on app/javascript/apps/diagram/components/Diagram/index.js
> +    // if (readOnly) {
Tu as lu le commentaire au moins? xD

2021-09-16 11:43 UTC, ManuBarchich commented on app/javascript/apps/form/QuestionForm/questionForm.js
> +                      disabled={deployedMode}
Oui

2021-09-21 13:36 UTC, quentingirard approved these changes

2021-09-22 06:26 UTC, merged